const HeroImage = require("../assets/hero.jpg");
export const LogoImage = require("../assets/logo.png");
export const primaryColor = "#018fa1";
export const styles = {
  container: {
    minHeight: "100vh",
    backgroundImage: `url(${HeroImage})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    padding: "16px",
  },
  logo: {
    // position: "absolute",
    // top: "16px",
    // left: "16px",
    width: "120px", // Adjust size as needed
    height: "auto",
  },
  userAvatar: {
    width: "40px",
    height: "40px",
    marginLeft: "auto",
    position: "absolute",
    top: "16px",
    right: "16px",
  },
  paper: {
    position: "relative",
    width: "100%",
    minHeight: "600px",
    display: "flex",
    justifyContent: "flex-end",
    borderRadius: "16px",
    overflow: "hidden",
    backgroundColor: "transparent",
  },

  rightPanel: {
    height: "600px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0px",
    backdropFilter: "blur(15px)",
    borderRadius: "16px",
    marginRight: "50px",
  },
  card: {
    width: "500px",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "12px",
    padding: "32px",
    backgroundColor: "rgba(255,255,255,0.85)",
  },
  header: {
    textAlign: "center",
    marginBottom: "32px",
  },
  title: {
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1976d2",
    marginBottom: "8px",
    margin: 0,
  },
  subtitle: {
    color: "#666",
    fontSize: "1rem",
    margin: 0,
  },
  toggleGroup: {
    display: "flex",
    backgroundColor: "#f5f5f5",
    borderRadius: "8px",
    padding: "4px",
    marginBottom: "32px",
    justifyContent: "center",
  },
  toggleButton: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "12px 24px",
    borderRadius: "6px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    fontWeight: 500,
    transition: "all 0.3s ease",
    fontSize: "14px",
  },
  toggleButtonActive: {
    backgroundColor: primaryColor,
    color: "white",
    boxShadow: "0 2px 8px rgba(25, 118, 210, 0.3)",
  },
  formGroup: {
    marginBottom: "24px",
    width: "100%",
  },
  label: {
    display: "block",
    marginBottom: "8px",
    fontWeight: 500,
    color: "#333",
    fontSize: "14px",
  },
  textField: {
    width: "100%",
    padding: "12px 16px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "16px",
    backgroundColor: "#f8f9fa",
    transition: "border-color 0.3s ease",
    outline: "none",
  },
  textFieldFocus: {
    borderColor: "#1976d2",
    boxShadow: "0 0 0 2px rgba(25, 118, 210, 0.2)",
  },
  loginButton: {
    width: "100%",
    padding: "12px",
    background: "linear-gradient(45deg, #018fa1 30%, #42a5f5 90%)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: 500,
    cursor: "pointer",
    marginBottom: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "transform 0.2s ease",
  },
  otpContainer: {
    textAlign: "center",
  },
  otpTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "#333",
    marginBottom: "8px",
    margin: 0,
  },
  otpSubtitle: {
    color: "#666",
    marginBottom: "32px",
    fontSize: "14px",
  },
  otpInputs: {
    display: "flex",
    gap: "8px",
    justifyContent: "center",
    marginBottom: "32px",
  },
  otpInput: {
    width: "48px",
    height: "48px",
    textAlign: "center",
    border: "2px solid #ddd",
    borderRadius: "8px",
    fontSize: "18px",
    fontWeight: 500,
    outline: "none",
    transition: "border-color 0.3s ease",
  },
  divider: {
    height: "1px",
    background: "#e0e0e0",
    margin: "24px 0",
  },
  link: {
    color: "#1976d2",
    textDecoration: "none",
    fontWeight: 500,
    cursor: "pointer",
  },
  backButton: {
    background: "transparent",
    border: "1px solid #1976d2",
    color: "#1976d2",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    marginTop: "16px",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
};
